# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qhy9jzpPVW7ISKz3hvZ2g6JYpgTagcF
"""

import streamlit as st
import torch
import textstat
from transformers import pipeline

# Load pretrained zero-shot classifier
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Sensational keywords common in financial misinformation
RISK_KEYWORDS = [
    "breaking", "urgent", "collapse", "secret", "leaked",
    "crisis", "bankruptcy", "insider", "dump", "panic",
    "liquidity crisis", "imminent crash"
]

def financial_risk_score(text):
    text_lower = text.lower()

    keyword_hits = sum([1 for word in RISK_KEYWORDS if word in text_lower])
    sensational_score = keyword_hits / len(RISK_KEYWORDS)

    readability = textstat.flesch_reading_ease(text)
    complexity_score = 1 - (readability / 100)

    candidate_labels = ["real financial news", "manipulated or fake financial news"]

    result = classifier(text, candidate_labels)
    ai_score = result["scores"][1]  # fake label probability

    final_score = (0.5 * ai_score) + (0.3 * sensational_score) + (0.2 * complexity_score)

    return round(final_score, 3), ai_score, sensational_score, complexity_score

def risk_label(score):
    if score > 0.75:
        return "🔴 HIGH RISK"
    elif score > 0.5:
        return "🟠 MEDIUM RISK"
    else:
        return "🟢 LOW RISK"

# ---------------- Streamlit UI ---------------- #

st.set_page_config(page_title="VeriMarket Deepfake Detector", layout="centered")

st.title("🔍 VeriMarket – Financial Deepfake Detector")
st.markdown("Detect potential AI-generated or manipulated financial news.")

text_input = st.text_area("Paste financial news or announcement here:")

if st.button("Analyze"):
    if text_input.strip() == "":
        st.warning("Please enter text.")
    else:
        final_score, ai_score, sensational_score, complexity_score = financial_risk_score(text_input)

        st.subheader("📊 Risk Assessment")
        st.metric("Final Manipulation Risk Score", final_score)
        st.write(risk_label(final_score))

        st.markdown("### 🔬 Model Breakdown")
        st.write(f"AI Classification Score: {round(ai_score,3)}")
        st.write(f"Sensationalism Score: {round(sensational_score,3)}")
        st.write(f"Text Complexity Score: {round(complexity_score,3)}")

        if final_score > 0.75:
            st.error("Escalation Recommended: Human Expert Review + Blockchain Anchoring")
        elif final_score > 0.5:
            st.warning("Manual review suggested.")
        else:
            st.success("Low probability of manipulation.")

streamlit run app.py